language: generic
sudo: enabled
  
before_install:
  - . ./compare-installer-vers-to-other-releases.sh
  - if [ "$NEW_VERSION" == 0 ]; then exit 0; fi

install:
  - sudo apt update -y -qq && sudo apt install makeself -y -qq
  
before_script:      
  - ". ./get-latest-container-ver-num.sh"
  - "./pull-pkg-docker-containers.sh -a"
  - "./download-docker-releases.sh"

script:
  - sed -i "s/__POC_VERSION__/$latest_poc/g; s/__MYSQL_VERSION__/$latest_mysql/g; s/__TOMCAT_VERSION__/$latest_tomcat/g" ./makeself/install-esaude/install-eSaude.sh
  - "./makeself/makeself.cmd"

before_deploy:
  - sed -i "s/__RELEASE_VERSION__/$installer_version/g; s/__POC_VERSION__/$latest_poc/g; s/__MYSQL_VERSION__/$latest_mysql/g; s/__TOMCAT_VERSION__/$latest_tomcat/g" desc.json

deploy:
  provider: bintray
  file: desc.json
  user: $BINTRAY_APIUSER
  key: $BINTRAY_APIKEY
  skip_cleanup: true
