language: generic
sudo: enabled
install:
- sudo apt update -y -qq && sudo apt install makeself -y -qq
before_script:
- ". ./get-latest-container-ver-num.sh"
- "./pull-pkg-docker-containers.sh -a"
script:
- sed -i "s/__POC_VERSION__/$latest_poc/g; s/__MYSQL_VERSION__/$latest_mysql/g; s/__TOMCAT_VERSION__/$latest_tomcat/g" ./makeself/install-esaude/install-eSaude.sh
- "./makeself/makeself.cmd"
before_deploy:
- ". ./makeself/install-esaude/get_version.sh"
- sed -i "s/__RELEASE_VERSION__/$installer_version/g; s/__POC_VERSION__/$latest_poc/g;
  s/__MYSQL_VERSION__/$latest_mysql/g; s/__TOMCAT_VERSION__/$latest_tomcat/g" desc.json
deploy:
  provider: bintray
  file: desc.json
  user:
    secure: XErydohw7eMZFXkBqJkJ2tpopCEMT54JBGo9ZJMZwtSFbj4vVTYO9R9x1EGnpvSssYc6ePK92rQo6nsx3Cyha1g2QVzSXWAwSejiBGmBnjNHpguOYfSDBOP2OGJg0BuoJ53l9TYjVzR44swaZh98qhmAMrc0keMpEPyg+QE772U9/RepykdrBeiR6PbcKYL8EOoSAHxHp32NHL70zJUQfhqPyQD9VerbaV81+/QltWjRDvWYzBO+F+WSVgdviFnWhfSy7Fhj8MISXmlYcxBY10ObZ/TVibEOi1s3y/vww1F14fhgNfuFIOaRjSAZU+qLWeaddi60ZaTW8T4TeDNchjrGPG9pn9K1UcUAeAqpk4px80tVb5pXkQY3kc06Jnj0XJkkJ1/p8Zqd2GG6eOYE8SU9I7iALgdCJ4w6PoxjDAghpqM7K5BhM7OrKYjbBqhd8KH1SS3P3QTiRfwIg2aAI+k3QOJEXtuaan1FMbrUJGiCoMn5hccnueVkhWLWx3ue7naiNFdddy1oOBeBt7lGstT+f4c2dCUanLMnjBpwDFBb3818RKu0iOlyGdRucR5mTymuYHhxEnuTDwMWGDvzif4KqpNl5nU/ArmL1J1xUCw7+foTbX6/MM7cZ96tGndLCp9xRideg7BFEXG33vkUkrFy0uWTyI1EHrBgC0uklLs=
  key:
    secure: ZDZ/ZyoZew7+GsETveJyeZEo2R1hFCTn/MAemJmxrZ8XT9gNtm6/A5EeGpAapWq1fQyTAtrhwv/Jk29ihR4QuAsPwAUEL39i4oZgFZIZMJAzVzXxPrXIJoa2/0FvBJ2TaDYwnEF7+4catb+tNP0V4BJEH9DnnmeGiuyrgUmsdQhF9uwjvgxJDxLEjr7IGXTjy0d0tD2kSDKMiesDAPBb3FZXbE0zLx3Zw7seH/TaknGyGQfd6FLDhN2LHBNgbKhC/8j9e2ACk6cOtj4xLw/lItrZBboA/hh3Ecb5bWAuXHib4EG9HswDT/cTuqj9XDXbkaBMuBdLAMO8WMcpucyOSwa2hgAv+GKiQPF3bAjZmWrNzNZYF72J3XN68iRga+D2oRAQZlxJ1LZh5GRKcf152P/BYaH4f2Xqw1Ur/qTGJUAcUsM3N4CLQW3V95gfqsFX9RUJPAFETXFPN1wgPmJDwzpzgn1V2iz+UK5zG9Fje2ZjdGbr9d3hTNDPEIWJxAOsmMmfOi/806sw+Z2yfc/os7Rag+755gQqyMsmEV1Zjwu2SNFAVybDgFp7PNqbkUGbEflz80bf7RDSQ/MrVuRnfcvYz3YiVM4sTieGjQaZKfQvvskuxNK9+4EDnIWBwcnSb1g6dh/gKL3r7ix2FQkdxwr9LIfhWRh1mv41jtaAR1M=
  skip_cleanup: true
